=== CubeEdge-Studios/backpack-locker/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "BUNDLE",
        "COSTUME",
        "HAT",
        "AVATAR",
        "TITLE",
        "MOUNT",
        "PET",
        "BACKBLING",
        "UNLOCK"
      ],
      "default": "BUNDLE"
    },

    "id": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    },
    "marketplace_id": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    },

    "game_id": {
      "type": "string",
      "enum": [
        "DR",
        "MURDER",
        "SKY",
        "CTF",
        "SG",
        "HIDE",
        "BED",
        "GRAV",
        "PARTY",
        "DROP",
        "BUILD",
        "GROUND",
        "BRIDGE",
        "PARKOUR",
        "WARS"
      ]
    },

    "unlock_id": {
      "type": "string",
      "enum": [
        "BED_FRAME",
        "BED_PILLOW",
        "BED_SHEET",
        "BED_TOPPER",
        "MERCHANT_SKIN",
        "PROJECTILE_TRAIL",
        "HUB_TITLE",
        "AVATAR",
        "COSTUME",
        "POWERUP",
        "ELIMINATION_MESSAGE",
        "ELIMINATION_SOUND",
        "ELIMINATION_BEACON",
        "LEAP_EFFECT",
        "TRAIL",
        "HAT",
        "GOAL_SKIN",
        "FLAG",
        "ITEM_STATION",
        "UPGRADE_STATION",
        "DEATH_SKIN",
        "RUNNER_CAPE",
        "DEATH_MARKER",
        "PORTAL_TAUNT",
        "PROJECTILE",
        "BLOCK_EYES",
        "BLOCK_LEGS",
        "ELIMINATION_PARTICLE",
        "BLOCK_HAT",
        "TAUNT",
        "HELMET",
        "GRAVESTONE",
        "GHOST_COLOR",
        "THROWABLE",
        "ZAPPER_TRAIL",
        "DEATH_CRATE",
        "ISLAND_FLAG",
        "SPAWN_VEHICLE",
        "ELIMINATION_EFFECT",
        "SPAWN_PEDESTAL",
        "AUTO_BRIDGER",
        "TREASURE",
        "TREASURE_PARTICLES"
      ]
    },

    "level_id": {
      "type": "string",
      "pattern": "^(\\d{1,3}|I|II|III|IV|V)$"
    },

    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },

    "icon": {
      "type": "string",
      "pattern": "^((https?://.*.(?:png|jpg))|(/.*.(?:png|jpg)))$"
    },
    "thumbnail": {
      "type": "string",
      "pattern": "^(https?://.*.(?:png|jpg))$"
    },

    "display_text": {
      "type": "string"
    },

    "price": {
      "type": "number",
      "minimum": 0
    },
    "currency": {
      "type": "string",
      "enum": ["MINECOIN"]
    },

    "tags": {
      "type": "array",
      "items": {
        "enum": [
          "UNOBTAINABLE",
          "PAID",
          "QUEST",
          "NEWSLETTER",
          "HUB_QUEST",
          "LIMITED"
        ]
      }
    },
    "released_at": {
      "type": "string",
      "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d([+-][0-2]\\d:[0-5]\\d|Z)$"
    },
    "bundle": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    }
  },

  "if": {
    "properties": { "type": { "const": "UNLOCK" } }
  },
  "then": {
    "required": ["type", "game_id", "unlock_id", "level_id", "name"]
  },
  "else": {
    "required": ["type", "id", "name"]
  },

  "dependencies": {
    "marketplace_id": ["id"],
    "price": ["currency"],
    "currency": ["price"]
  },

  "additionalProperties": false
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/burger_gold_edition_costume/burger_gold_edition_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "fa7188b5-6676-4028-acf1-42741f0a3ba9",
  "marketplace_id": "fa7188b5-6676-4028-acf1-42741f0a3ba9",
  "name": "Burger: Gold Edition Costume",
  "description": "The delicious burger costume you know and love, now in an epic gold variant. It doesnâ€™t get better than this!\r\n\r\nFeatures:\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"The Gold Edition\" hub title\r\n+ Includes \"Royal Burger\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets002.xboxlive.com/serviceid-18231953-4b1d-472c-a39e-48b10105b7b7/63c76458-03b1-42a8-aebb-3ad38b02098f/burgergold_Thumbnail_0.jpg",
  "price": 310,
  "currency": "MINECOIN",
  "released_at": "2019-06-27T10:00:00Z"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/cactus_costume/cactus_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "2525b0b9-31a9-4fcf-919e-819817eddcc1",
  "marketplace_id": "2525b0b9-31a9-4fcf-919e-819817eddcc1",
  "name": "Cactus Costume",
  "description": "This costume will definitely grow on you! Just stay away from balloons...\r\n\r\nFeatures:\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"The Spikey\" hub title\r\n+ Includes \"Adorable Cactus\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets001.xboxlive.com/serviceid-18231953-4b1d-472c-a39e-48b10105b7b7-public/68b1357a-c2c8-456c-ad61-44ae9dcf8cf7/cactus_Thumbnail_0.jpg",
  "price": 160,
  "currency": "MINECOIN",
  "released_at": "2019-03-22T10:00:00+00:00"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/fineapple_costume/fineapple_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "094fd0a0-5528-4883-9f0c-f279d7ce82cc",
  "marketplace_id": "094fd0a0-5528-4883-9f0c-f279d7ce82cc",
  "name": "Fineapple Costume",
  "description": "Pineapples are people too, right?\r\n\r\nFeatures:\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"LOOKIN' PINE\" hub title\r\n+ Includes \"Summer Pineapple\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets002.xboxlive.com/pf-title-b63a0803d3653643-20ca2/e2a8ed73-b0fd-4d70-b1d7-d7d1c977b227/fineapple_Thumbnail_0.jpg",
  "price": 160,
  "currency": "MINECOIN",
  "released_at": "2020-07-24T17:00:00Z"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/juicy_costume/juicy_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "a65c6795-bb7c-4aed-b4b4-9c60d2eb3db8",
  "marketplace_id": "a65c6795-bb7c-4aed-b4b4-9c60d2eb3db8",
  "name": "Juicy Costume",
  "description": "Tomatoes are fruit. It's important you know that.\r\n\r\nFeatures:\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"Ketchup with me!\" hub title\r\n+ Includes \"Cute Tomato\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets001.xboxlive.com/pf-title-b63a0803d3653643-ee7b/61a9c8df-37f4-4c07-8d8b-915379cf69b3/juicy_Thumbnail_0.jpg",
  "price": 160,
  "currency": "MINECOIN",
  "released_at": "2020-01-16T01:00:00+00:00"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/hip_hop_costume/hip_hop_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "03dbb32d-0f33-4c12-a481-5833425116d4",
  "marketplace_id": "03dbb32d-0f33-4c12-a481-5833425116d4",
  "name": "Hip Hop Costume",
  "description": "Itâ€™s time to jump for joy with this FREE costume!\n\nFeatures:\n+ Custom 3D geometry that makes you stand out from the crowd!\n+ Works in hubs and games\n+ Includes \"Ribbit\" hub title\n+ Includes \"Cute Frog\" avatar\n\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets001.xboxlive.com/serviceid-18231953-4b1d-472c-a39e-48b10105b7b7/09821698-6401-4725-8e86-34a7108e90f1/hiphop_Thumbnail_0.jpg",
  "price": 0,
  "currency": "MINECOIN",
  "released_at": "2019-08-09T10:00:00+00:00"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/battle_burger_costume/battle_burger_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "a9ab2eda-c93f-402b-8cb0-5facbbf6dd3b",
  "marketplace_id": "a9ab2eda-c93f-402b-8cb0-5facbbf6dd3b",
  "name": "Battle Burger Costume",
  "description": "Ketchup with this costume if you can!\r\n\r\nFeatures:\r\n\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"FOOD FIGHT!\" hub title\r\n+ Includes \"Mega Burger\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets001.xboxlive.com/pf-title-b63a0803d3653643-20ca2/241d4eb1-e8ff-4139-a800-4f205e74467c/battleburger_Thumbnail_0.jpg",
  "price": 310,
  "currency": "MINECOIN",
  "released_at": "2021-10-07T17:00:00+00:00"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/grim_creeper_costume/grim_creeper_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "50b1c5e1-116e-42d8-80a7-90cae41c1fcd",
  "marketplace_id": "50b1c5e1-116e-42d8-80a7-90cae41c1fcd",
  "name": "Grim Creeper Costume",
  "description": "It's time to get super spoopy!\r\n\r\nFeatures:\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"CREEPER? AW MAN!\" hub title\r\n+ Includes \"Grim Creeper\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets002.xboxlive.com/pf-title-b63a0803d3653643-ee7b/606b784a-8280-4c07-9ec4-16a5f05dc62b/Thumbnail_0.jpg",
  "price": 160,
  "currency": "MINECOIN",
  "released_at": "2019-10-10T10:00:00+00:00"
}

=== CubeEdge-Studios/backpack-locker/bundles/marketplace/hoodie_duck_costume/hoodie_duck_costume_bundle.json
{
  "type": "BUNDLE",
  "id": "4cb3c1ff-ae99-4f77-8eb6-c9f200e50ca6",
  "marketplace_id": "4cb3c1ff-ae99-4f77-8eb6-c9f200e50ca6",
  "name": "Hoodie Duck Costume",
  "description": "Quack. Quack quack, quack quack. Quack? Quack!\r\n\r\nFeatures:\r\n+ Custom 3D geometry that makes you stand out from the crowd!\r\n+ Works in hubs and games\r\n+ Includes \"You quack me up!\" hub title\r\n+ Includes \"Detective Duck\" avatar\r\n\r\nNote: This costume only works on The Hive server",
  "thumbnail": "https://xforgeassets002.xboxlive.com/pf-title-b63a0803d3653643-ee7b/4db1fed7-08f6-4698-9685-52c8882d3073/hoodieduck_Thumbnail_0.jpg",
  "price": 160,
  "currency": "MINECOIN",
  "released_at": "2020-02-13T09:00:00+00:00"
}
